# Generated by Django 6.0.4 on 2026-04-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='end_page',
            new_name='page_number',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='start_page',
        ),
    ]
